### PR TITLE
Allow @ in login name

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

Login name may contain @, especially AD/LDAP logins.
This PR then adds `@` as a valid login character.
Tested with 1.10, works perfectly.

In develop branch, sounds like the corresponding code is here, however I did not test it :
https://github.com/Libertempo/Libertempo-web/blob/83da2ee581ef2448016720ec90c1008512f7d926/App/ProtoControllers/HautResponsable/Utilisateur.php#L727

Thank you 👍 

Ben

### CODE REVIEW

**Comment by wouldsmina** [comment]
Hi @benrubson,
you have to use the develop branch. Thank you.

**Comment by benrubson** [comment]
Thank you @wouldsmina for your answer.
Unfortunately I did not have the opportunity to test development branch, as I run the stable version into production.
Our AD uses `username@dom.com` like usernames, so I had to use this PR for AD connectivity to work.
Sounds like I found the development corresponding line as per my first post.
Would it be OK for you ?
Thank you 👍

**Comment by Prytoegrian** [comment]
No, hum, what @wouldsmina is trying to say is similar to what I said few days ago : https://github.com/Libertempo/Libertempo-web/pull/628#issuecomment-386562471.

**Comment by benrubson** [comment]
@Prytoegrian I've updates the branch, unfortunately the PR does not merge with the develop branch.
As said above :
- the PR works nicely with 1.10 ;
- I think I've found the code to modify in develop branch, but did not test it.

Thank you 👍

**Comment by Prytoegrian** [comment]
I see. It seems Github doesn't fully understand this base branch change, and I can't accept this PR as is. I propose you to delete this PR and recreate one with changes in `Utilisateur:727`. It won't take too long, especially directly on Github. Once done that, we'll merge your changes (I tested them, it works like a charm !)

Thanks for your time.

**Comment by benrubson** [comment]
Glad to see you successfully tested it on develop branch.
Here is then the reworked PR : #646.
Thank you 👍

**Pull request closed without merging**
